package controllers

var botResponses = []string{
	"Axe", "Abalone", "Abacus", "Admin", "Arrow", "Abandon", "Ability", "Able", "About", "Above", "Abroad", "Absence", "Absent", "Absolute", "Abstract", "Abuse", "Abusive", "Academic", "Accede", "Accept", "Acceptable", "Acceptance", "Access", "Accident", "Accolade", "Accompany", "Accomplish", "Accord", "According+to", "Account", "Accountant", "Accurate", "Accuse", "Ache",
	"Board", "Boom", "Bar", "Bomb", "Bingo", "Ball", "Black", "Bid", "Bear", "Boat", "Babe", "Bubble", "Bowie", "Baby", "Bachelor's", "Back", "Backboard", "Background", "Backhand", "Backup", "Backward", "Bacterium", "Bad", "Badly", "Bag", "Baggage", "Bake", "Balance", "Ball", "Band", "Bandage", "Bane", "Bang", "Bank", "Banker", "Bankrupt", "Bankruptcy", "Banter", "Bar", "Barber", "Bare",
	"Count", "Cloud", "Cup", "Care", "Carrot", "Corn", "Corndog", "Coliflower", "Comma", "Coal", "Cage", "Cake", "Calculate", "Calculation", "Calendar", "Calf", "Call", "Callous", "Calm", "Camera", "Camp", "Campaign", "Campus", "Can", "Cancel", "Cancer", "Candid", "Candidate", "Candy", "Cap", "Capable", "Capacity", "Capital", "Captain", "Capture", "Car",
	"Death", "Deep", "Dance", "Duck", "Dock", "Dino", "Dinosaur", "Drink", "Dark", "Desk", "Dust", "Damn", "Dad", "Daily", "Dam", "Damage", "Damages", "Damp", "Dance", "Danger", "Dangerous", "Dare", "Dark", "Data", "Date", "Daughter", "Dawn", "Day", "Dead", "Deaf", "Deal", "Dear", "Dearth",
	"Ears", "Eager", "Eagle", "Early", "Earth", "Exotic", "Electro", "Ernest", "Each", "Eager", "Ear", "Earlier", "Earlobe", "Early", "Earn", "Earth", "Ease", "East", "Easy", "Easygoing", "Eat", "Ecology", "Economic", "Economics", "Economist", "Economy", "Ecosystem", "Edge", "Edict", "Edit",
	"Faint", "Face", "Fact", "Fabric", "Failure", "Fail", "Faith", "Faint", "Fake", "Factor", "Factory", "Faculty", "Failure", "Faint", "Fair", "Faith", "Fake", "Fall", "False", "Fame", "Familiar", "Family", "Famous", "Fan", "Fancy", "Far",
	"Gone", "Gain", "Gain", "Gallon", "Game", "Gap", "Garage", "Garbage", "Garden", "Gas", "Gate", "Gate", "Gather", "Gay", "Gear", "Gender", "Gene", "General", "Generally", "Generate", "Generate", "Generation", "Generosity", "Generous", "Gentle", "Gentleman", "Genuine", "Geography", "Geothermal", "Get", "Giant",
	"Habit", "Habitat", "Hail", "Hair", "Half", "Hammer", "Hand", "Handle", "Handsome", "Handwriting", "Hang", "Happen", "Happy", "Harbor", "Hard", "Hardly", "Hardware", "Harm", "Harsh", "Harvest", "Hat", "Home",
	"I", "Ideal", "Ice", "Idea", "Ideal", "Identical", "Identification", "Identify", "Identity", "If", "Ignominy", "Ignore", "Ill", "Illegal", "Illness", "Illustrate", "Image", "Imaginary", "Imagination", "Imaginative", "Imagine", "Imitate", "Immediate", "Immigrant", "Immoral", "Impact", "Impatience", "Impatient",
	"Jacket", "Jail", "Jam", "Jar", "Jargon", "Jaw", "Jealous", "Jealousy", "Jelly", "Jet", "Jewel", "Jeweler", "Jewelry", "Jibe", "Job", "Join", "Joint", "Joke", "Journal", "Journey", "Joy", "Judge", "Judgment", "Juice",
	"Koala", "Keen", "Keep", "Key", "Kick", "Kickoff", "Kid", "Kill", "Kind", "Kindness", "King", "Kingdom", "Kiss", "Kitchen", "Knee", "Kneel", "Knife", "Knit", "Knock", "Knot", "Know", "Knowledge", "Knuckle",
	"Limp", "Label", "Labor", "Laboratory", "Lack", "Ladder", "Lady", "Lake", "Lamp", "Land", "Landfill", "Landing", "Landlord", "Lane", "Language", "Large", "Last", "Late", "Lately", "Later", "Latter", "Laugh",
	"Martir", "Machine", "Mad", "Magazine", "Magic", "Mail", "Main", "Maintain", "Major", "Majority", "Make", "Male", "Malice", "Man", "Manage", "Management", "Manager", "Manner", "Manufacture", "Many", "Map", "March", "Margin", "Mark",
	"Nope", "Nail", "Naked", "Name", "Narrow", "Nation", "National", "Native", "Natural", "Naturally", "Nature", "Nausea", "Navy", "Near", "Nearby", "Nearly", "Neat", "Necessary", "Neck", "Need", "Needle", "Negative", "Negligence", "Negligent", "Neighbor",
	"O", "Opera", "Oath", "Obdurate", "Obey", "Object", "Objection", "Objective", "Observation", "Observe", "Obsessive", "Obtain", "Obviate", "Obvious", "Occasion", "Occasionally", "Occupation", "Occupy", "Occur", "Ocean", "October", "Odd", "Odor", "Of", "Off", "Offend", "Offense",
	"Parts", "Pace", "Pack", "Package", "Pad", "Page", "Pain", "Painful", "Paint", "Painter", "Painting", "Pair", "Pale", "Palm", "Pan", "Panel", "Panic", "Pants", "Paper", "Parade", "Paragraph", "Parallel", "Paraphrase", "Parent", "Park", "Parliament",
	"Queen", "Quad", "Qualification", "Qualify", "Quality", "Quantity", "Quarter", "Quarterback", "Quarterly", "Queen", "Querulous", "Question", "Quick", "Quiet", "Quit", "Quite", "Quiz", "Quotation", "Quote",
	"Roast", "Race", "Racial", "Radiation", "Radical", "Radio", "Rage", "Rail", "Railroad", "Rain", "Raise", "Range", "Rank", "Rapid", "Rare", "Rarely", "Rash", "Rate", "Rather", "Ratio", "Rational", "Raw", "Reach",
	"Toast", "Sacrifice", "Sad", "Sadness", "Safe", "Safety", "Sail", "Sake", "Salad", "Salary", "Sale", "Salesman", "Salesperson", "Saleswoman", "Salt", "Same", "Sample", "Sand", "Sandwich", "Sarcastic", "Satisfaction", "Satisfy", "Saturday", "Sauce", "Save", "Savings", "Say", "Scale",
	"Under", "Ugly", "Umbrella", "Umpire", "Unable", "Uncle", "Under", "Underdog", "Undergo", "Undergraduate", "Underground", "Underneath", "Understand", "Understanding", "Undertake", "Undertaker", "Undo", "Unemployed", "Unemployment", "Unfortunate", "Unfortunately", "Unhappiness", "Unhappy", "Uniform", "Union", "Unique", "Unit", "Unite", "Universal", "Universe", "University",
	"Vain", "Vacation", "Vagina", "Valley", "Valuable", "Value", "Variation", "Variety", "Various", "Vary", "Vast", "Vegetable", "Vehicle", "Verb", "Verdict", "Version", "Very", "Vessel", "Vestige", "Veterinarian", "Victim", "Victory", "Video", "Videographer", "View", "Vilify", "Village",
	"Wallaby", "Wage", "Waist", "Wait", "Waiter", "Waiting", "Waitress", "Waive", "Wake", "Walk", "Wall", "Wallet", "Wander", "Want", "War", "Warm", "Warmth", "Warn", "Warning", "Wash", "Waste", "Watch", "Water", "Wave", "Wax", "Way", "We", "Weak",
	"Xerox",
	"Yellow", "Yard", "Yawn", "Yeah", "Year", "Yearly", "Yell", "Yellow", "Yes", "Yesterday", "Yet", "You", "Young", "Your", "Yours", "Yourself", "Youth",
	"Zombie", "Zealot", "Zenith", "Zero", "Zipper", "Zone", "Zoo",
}

var botNames = []string{
	"Halliday",
	"AJLA",
	"jACk",
	"Stuart",
	"iAN",
	"Steve",
	"ElI",
	"thanus",
	"RuBy",
	"Max",
	"Jimbo",
	"Matter",
	"Stuart",
	"Jane",
	"marajade",
	"fldsmdfr",
	"x-women",
	"presidentLopez",
	"theWho",
	"4ever",
	"michaelMy",
	"rossano",
	"tottttto",
	"ironguy",
	"fam",
	"N1N4",
}
